In [14]:
%load_ext autoreload
%autoreload 2

from __future__ import absolute_import, division, print_function, unicode_literals

import math
import numpy as np
import time

from hdbscan import HDBSCAN
from tilesets.models import Tileset
from fragments.utils import cluster_fragments
from sklearn.utils.extmath import cartesian
from sklearn.metrics.pairwise import pairwise_distances

from matplotlib.pyplot import imshow
import matplotlib.pyplot as plt
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [13]:
tile_set_uuids = ['gigapan-54825-snapshots']
z = 2
x_from = 0
x_to = 454330
y_from = 0
y_to = 149278
width = 600
height = 200
i_min = 16
i_max = 64
t = 16
n = 4

In [1]:
try:
    # Map UUIDs to tile set objects
    tile_sets = list(map(
        lambda uuid: Tileset.objects.get(uuid=uuid),
        tile_set_uuids
    ))
except Tileset.DoesNotExist as e:
    print('SCHISS')
    tile_sets = []

out = cluster_fragments(
    tile_sets=tile_sets,
    zoom_level=z,
    x_from=x_from,
    x_to=x_to,
    y_from=y_from,
    y_to=y_to,
    width=width,
    height=height,
    inset_disp_size_min=i_min,
    inset_disp_size_max=i_max,
    inset_thres=t,
    min_cluster_size=n,
)

imshow(out['ass'])

del out['ass']

print(out)

NameError: name 'tile_set_uuids' is not defined

In [12]:
a = np.array([[5,2],[2,3],[7,9],[-1,4],[5,10]])
ass = np.array([0,1,1,0,1])
a[np.where(ass == 1)].shape

3

In [28]:
print(pairwise_distances(a))
print(np.sum(pairwise_distances(a), axis=0))
print(a.shape[0])
print(np.sum(pairwise_distances(a), axis=0) / (a.shape[0] - 1))
print(np.mean(np.sum(pairwise_distances(a), axis=0) / (a.shape[0] - 1)))
print(np.mean(pairwise_distances(a), axis=0))

[[0.         3.16227766 7.28010989 6.32455532 8.        ]
 [3.16227766 0.         7.81024968 3.16227766 7.61577311]
 [7.28010989 7.81024968 0.         9.43398113 2.23606798]
 [6.32455532 3.16227766 9.43398113 0.         8.48528137]
 [8.         7.61577311 2.23606798 8.48528137 0.        ]]
[24.76694287 21.7505781  26.76040867 27.40609549 26.33712246]
5
[6.19173572 5.43764453 6.69010217 6.85152387 6.58428061]
6.351057379551956
[4.95338857 4.35011562 5.35208173 5.4812191  5.26742449]


In [2]:
import json
json.dumps({ 1: 'ass' })

'{"1": "ass"}'

In [4]:
'ass' if NaN else 'hole'

NameError: name 'NaN' is not defined